services:

  frontend:
    build: ./frontend
    ports:
      - "8080:80"


  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"

  # DATABASE SERVICE
  database:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # GRAFANA MONITORING
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - backend

volumes:
  db_data:
